#!/bin/sh

script_name='dmenu-editor-history'
install_dir='/usr/local/bin'

case $1 in
    '') cp "./$script_name" "$install_dir" ;;
    uninstall) rm "$install_dir/$script_name" ;;
    *) echo 'Invalid argument' && exit 1
esac

